#!/usr/bin/python

import epi

args = epi.read_terminal_args();    # read args from terminal 

# print(args);
dl_option = args['_dl_option'];
maximum_dlcnt = args['_maximum_dlcnt'];
ifpath = args['_ifpath'];
ofpath = args['_ofpath'];
dumpfpath = args['_dumpfpath'];
loadfpath = args['_loadfpath'];
dump = not not dumpfpath;
load = not not loadfpath;
preselect = args['_preselect'];

x = epi.crawler(\
    _dl_option = dl_option,\
    _maximum_dlcnt = maximum_dlcnt,\
    _ifpath = ifpath,\
    _ofpath = ofpath,\
    _dumpfpath = dumpfpath,\
    _loadfpath = loadfpath,\
    _preselect = preselect\
    );

x.run(dump = dump, load = load, );


# x.search();
# x.download();
# x.close();
