#!/usr/bin/python
#-*- coding: utf-8 -*-
__author__ = "Blurgy";

"""
Runs on python 3+
Converts .m3u8 document into .ts video 
"""

import os
import sys
import epi
from epi.globalfunctions import *


if(len(sys.argv) <= 1):
	print("Usage:\n\t./convert [$M3U8_FILE_NAME, ]\n\n");
	# print("E.g.:");
	# print("\tconvert 1.m3u8 blabla mp4\n\t# Download the video as blabla.mp4\n\t---------------------------------------------------------")
	# print("\tconvert 1.m3u8 blabla\n\t# Download the video as blabla.ts\n\t---------------------------------------------------------");
	# print("\tconvert 1.m3u8 blabla.mp4\n\t# Download the video as blabla.mp4.ts\n\t# (weird, but yes, for there's no second parameter given)\n");
# 	print(\
# """\t\033[33m-- NOTE: i am not expecting $SAVE_VIDEO_NAME to have an
# \t   extenson name such as '.mp4' or whatever. this script
# \t   will always append '.ts' after $SAVE_VIDEO_NAME.
# \t-- \033[31mbut $M3U8_FILE_NAME does have to be an existing path\033[0m"""\
# );
	exit();

files_to_download = [];
for i in range(len(sys.argv)):
	if(i == 0):
		continue;
	if(os.path.exists(sys.argv[i]) and os.path.isfile(sys.argv[i])):
		fname = sys.argv[i];
		files_to_download.append(fname);

for fname in files_to_download:
	x = epi.m3u8(_from_file = fname);
	x.download(split_fname(fname));
