#!/usr/bin/python3
#-*- coding: utf-8 -*-
__author__ = "Blurgy";

"""
Runs on python 3+
Converts .m3u8 document into .ts video 
1st argument: $M3U8_FILENAME
2nd argument(if exists): $download directory
"""

import os
import sys
import epi
from epi.globalfunctions import *


from_file = None;
dldir = None;
if(len(sys.argv) == 1):
	raise Exception("Too few arguments");
if(len(sys.argv) > 3):
	raise Exception("Too many arguments");

if(len(sys.argv) >= 2):
	from_file = sys.argv[1];
if(len(sys.argv) == 3):
	dldir = sys.argv[2];
	if(not os.path.exists(dldir)):
		os.makedirs(dldir);
	# os.chdir(dldir);
	dldir = os.path.join(os.getcwd(), dldir);

x = epi.m3u8(_from_file = from_file);
x.download(dldir);
